[project]
name = "moonbug"

[api]
port = 54321

[db]
port = 54322

[auth]
port = 54323

[smtp]
port = 54324

[storage]
port = 54325

[realtime]
port = 54326

[studio]
port = 54327

[auth.external.github.enabled] = false
[auth.external.gitlab.enabled] = false
[auth.external.google.enabled] = false

[auth.smtp.host] = "127.0.0.1"
[auth.smtp.port] = 54324
[auth.smtp.user] = "inbucket"
[auth.smtp.pass] = ""
[auth.smtp.admin_email] = "admin@localhost"
[auth.smtp.sender_name] = "Moonbug"